### PR TITLE
fix!: searchbar suggestions not showing up on Firefox Android

### LINKED ISSUE #163: bug: searchbar suggestions not showing up on Firefox Android
### Describe the bug

If the keyboard is open, searchbar results are not visible. They are only visbile when keyboard is closed

### To reproduce

Open http://atlas.ourkolkata.in/app/pandals and try searching something in the searchbar in Firefox Android

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dyslex7c**
Closes #163 

## Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/blob/dev/CONTRIBUTING.md)
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

fixed bug where searchbar suggestions were not showing up if the keyboard was opened in Firefox browser

---

## Screenshots

_[Screenshots]_

### CODE REVIEW

File: src/components/app/shared/Search/input.tsx [hunk 1]
```diff
@@ -138,18 +138,27 @@ export const SearchSuggestions = () => {
     if (window.location.pathname !== '/app/pandals') window.location.href = '/app/pandals';
   };
 
+  const classNames =
+    navigator.userAgent.toLowerCase().indexOf('firefox') > -1
+      ? cn(
+          'absolute z-[100] hidden data-[active=true]:flex flex-col',
+          'w-full px-3 h-fit max-h-100dvh overflow-hidden overflow-y-auto',
```
Comment (wriddhi) [inline src/components/app/shared/Search/input.tsx:145]:
```suggestion
          'w-full px-3 h-fit max-h-50dvh overflow-hidden overflow-y-auto',
```

try this

**Review by wriddhi — APPROVED** [review]
LGTM
