### PR TITLE
fix(client): add max width for wide displays

### LINKED ISSUE #274: bug: add max width for wide displays
For wider screens, the content should stop expanding after a certain threshold.<br>How it is right now

Example of how it should be:

### PR DESCRIPTION
**Pull request by Priyadharshini0101**
Closes #274

## Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/Pujo-Atlas-Kolkata/PujoAtlasKol-Web/blob/dev/CONTRIBUTING.md)
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

add max width for wide displays

---

## Screenshots
Screenshot (912)
Screenshot (916)
Screenshot (917)
Screenshot (931)
Screenshot (932)
Screenshot (936)
Screenshot (937)
Screenshot (938)

## Summary by CodeRabbit

* **Style**
  * Improved layout consistency on very large screens by adding maximum width constraints and horizontal centering to the homepage containers, navbar, footer, and key page sections including About Us and Sponsor Us pages.

### CODE REVIEW

File: src/app/sponsor-us/page.tsx [hunk 1]
```diff
@@ -9,20 +9,20 @@ import { PostHogEvents } from "@/providers";
...
 export default function SponsorUsPage() {
   return (
-    <main className="mt-24 mr-2 ml-2 flex flex-col backdrop-blur-xs sm:mt-36 sm:mr-0 sm:ml-10">
+    <main className="mx-auto mt-24 flex w-full max-w-screen-xl flex-col backdrop-blur-xs sm:mt-36">
       <div className="w-full rounded-2xl border-gray-500">
         <div className="flex flex-col gap-y-2 px-2 lg:px-0">
           <p className="text-3xl font-bold sm:text-5xl">Sponsor Pujo Atlas</p>
 
-          <p className="w-full pt-2 text-base leading-tight font-normal sm:w-[60dvw] sm:text-lg">
+          <p className="mx-auto w-full max-w-screen-xl pt-2 text-base leading-tight font-normal sm:w-[60dvw] sm:text-lg">
```
Comment (AyanavaKarmakar) [inline src/app/sponsor-us/page.tsx:17]:
```suggestion
          <p className="mx-auto w-full max-w-screen-xl pt-2 text-base leading-tight font-normal sm:text-lg">
```

**Review by AyanavaKarmakar — APPROVED** [review]
